[package]
name = "maru"
version = "0.1.0"
authors = ["extrasharp <genericpb@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gl = "0.14.0"
image = "0.23.6"
memoffset = "0.5.4"
cgmath = "0.17.0"
num = "0.3.0"
num-derive = "0.3.0"

[dependencies.glfw]
version = "0.38.0"
features = ["image"]

[patch.crates-io]
image = { path = "../_dld/image" }
