[package]
name = "maru"
version = "0.1.0"
authors = ["extrasharp <genericpb@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gl = "0.14.0"
image = "0.23.7"
memoffset = "0.5.4"
nalgebra = "0.21"
approx = "*"
nalgebra-glm = "0.7"
# num = "0.3.0"
# num-derive = "0.3.0"
num-traits = "0.2"

[dependencies.glfw]
version = "0.38.0"
features = ["image"]
